/**
 * Technical words a complete beginner wouldn't know. The course must explain each one in a
 * jargon box (with an everyday analogy) before using it: in the same lesson, or in an earlier
 * lesson of every track that reaches this one. `src/content/lessons.test.ts` enforces it.
 *
 * `term` must match a jargon box's `term` (or one of its `also` names). Patterns are written to
 * avoid everyday meanings (a "function" at a party, a POS "agent", "lead with benefits").
 */
export const jargon: { term: string; match: RegExp }[] = [
  // Day 1: brand and the AI chat
  { term: "AI", match: /\bAI\b/ },
  { term: "Prompt", match: /\bprompts?\b/i },
  { term: "Browser", match: /\bbrowsers?\b/i },
  { term: "Brand kit", match: /\bbrand kits?\b/i },
  { term: "Brand voice", match: /\bbrand voice\b|\bvoice words?\b/i },
  { term: "Hex code", match: /\bhex\b/i },
  { term: "Pixel", match: /\b\d+\s?px\b|\bpixels?\b/i },
  { term: "Contrast ratio", match: /\bcontrast\b/i },
  { term: "WCAG", match: /\bWCAG\b/ },
  // Day 2: planning and words
  { term: "Wireframe", match: /\bwireframes?\b/i },
  { term: "Mobile-first", match: /\bmobile-first\b/i },
  { term: "Hero", match: /\bhero\b/i },
  { term: "Subhead", match: /\bsubheads?\b|\bsubheadline\b/i },
  { term: "Call to action", match: /\bcall[- ]to[- ]action\b|\bCTAs?\b/i },
  { term: "Conversion", match: /\bconversions?\b|\bconverts\b/i },
  { term: "Placeholder", match: /\bplaceholders?\b/i },
  { term: "Design brief", match: /\bdesign brief\b/i },
  // Day 3: files, hosting, the build loop
  { term: "File and folder", match: /\bfolders?\b/i },
  { term: "File size", match: /\b\d+(\.\d+)?\s?(KB|MB|GB)\b|\bkilobytes?\b|\bmegabytes?\b/ },
  { term: "HTML", match: /\bHTML\b/ },
  { term: "CSS", match: /\bCSS\b/ },
  { term: "Code editor", match: /\bcode editors?\b/i },
  { term: "IDE", match: /\bIDEs?\b/ },
  { term: "Coding agent", match: /\bcoding agents?\b|\bagentic\b/i },
  { term: "Project brief", match: /\bproject brief\b/i },
  { term: "Web address", match: /\bweb address(es)?\b|\bURLs?\b/ },
  { term: "Domain", match: /\bdomains?\b/i },
  { term: "Subdomain", match: /\bsubdomains?\b/i },
  { term: "Hosting", match: /\bhost(ing|ed|s)?\b/i },
  { term: "Deploy", match: /\bdeploy(s|ed|ing|ments?)?\b/i },
  // Day 4: the full site
  { term: "Component", match: /\bcomponents?\b/i },
  { term: "JavaScript", match: /\bJavaScript\b|\bJS\b/ },
  { term: "Form service", match: /\bform services?\b/i },
  { term: "Access key", match: /\baccess keys?\b/i },
  // Day 5: landing pages
  { term: "Landing page", match: /\blanding pages?\b/i },
  { term: "Objection", match: /\bobjections?\b/i },
  { term: "Risk reversal", match: /\brisk reversal\b/i },
  { term: "Above the fold", match: /\b(above|below) the fold\b/i },
  // Day 6: speed and access
  { term: "Responsive design", match: /\bresponsive\b/i },
  { term: "Developer tools", match: /\bdeveloper tools\b|\bdevtools\b|\bF12\b/i },
  { term: "Page weight", match: /\bpage weight\b/i },
  { term: "WebP", match: /\bWebP\b/i },
  { term: "Lazy loading", match: /\blazy[- ]load(s|ing|ed)?\b/i },
  { term: "Core Web Vitals", match: /\bCore Web Vitals\b|\bLCP\b|\bINP\b|\bCLS\b/ },
  { term: "Accessibility", match: /\baccessib(le|ility)\b/i },
  { term: "Screen reader", match: /\bscreen readers?\b/i },
  { term: "Alt text", match: /\balt text\b|\balt=/i },
  { term: "Heading levels", match: /\bH[1-6]s?\b/ },
  // Day 7: going live properly
  { term: "Repository", match: /\brepositor(y|ies)\b|\brepos?\b/i },
  { term: "Commit", match: /\bcommit(s|ted|ting)?\b/i },
  { term: "Git", match: /\bGit\b/ },
  { term: "Analytics", match: /\banalytics\b/i },
  { term: "Registrar", match: /\bregistrars?\b/i },
  { term: "DNS", match: /\bDNS\b/ },
  { term: "Nameserver", match: /\bnameservers?\b/i },
  { term: "DNS record", match: /\b(A|CNAME|TXT|MX) records?\b|\bDNS records?\b/ },
  { term: "HTTPS", match: /\bHTTPS\b|\bSSL\b/ },
  { term: "Propagation", match: /\bpropagat(e|es|ion|ing)\b/i },
  // Day 8: bookings
  { term: "Booking system", match: /\bbooking systems?\b/i },
  { term: "No-show", match: /\bno-shows?\b/i },
  { term: "Embed", match: /\bembed(s|ded|ding)?\b/i },
  { term: "Payment page", match: /\bpayment pages?\b/i },
  { term: "Test mode", match: /\btest mode\b|\btest cards?\b|\btest keys?\b/i },
  // Day 9: stores and the server
  { term: "Server", match: /\bservers?\b/i },
  { term: "Serverless function", match: /\bserverless\b|\b(Cloudflare|Pages) Functions?\b|\bfunctions folder\b/i },
  { term: "API", match: /\bAPIs?\b/ },
  { term: "Secret key", match: /\bsecret keys?\b|\bpublic keys?\b|\bAPI keys?\b/i },
  { term: "Environment variable", match: /\benvironment variables?\b|\bVariables and Secrets\b/i },
  { term: "Kobo", match: /\bkobo\b/i },
  { term: "Webhook", match: /\bwebhooks?\b/i },
  // Day 10: web apps
  { term: "Web app", match: /\bweb apps?\b/i },
  { term: "Authentication", match: /\bauthenticat(e|es|ed|ion)\b/i },
  { term: "Authorisation", match: /\bauthori[sz]ation\b/i },
  { term: "Database", match: /\bdatabases?\b/i },
  { term: "SQL", match: /\bSQL\b/ },
  { term: "Row Level Security", match: /\bRow Level Security\b|\bRLS\b/ },
  { term: "Publishable key", match: /\bpublishable keys?\b/i },
  // Day 11: Google
  { term: "SEO", match: /\bSEO\b/ },
  { term: "Keyword", match: /\bkeywords?\b/i },
  { term: "Search intent", match: /\bsearch intent\b|\bintent\b/i },
  { term: "Title tag", match: /\btitle tags?\b/i },
  { term: "Meta description", match: /\bmeta descriptions?\b|\bmeta tags?\b/i },
  { term: "Internal link", match: /\binternal links?\b/i },
  { term: "Schema", match: /\bschema\b|\bstructured data\b|\bJSON-LD\b/i },
  { term: "Sitemap", match: /\bsitemaps?\b/i },
  { term: "robots.txt", match: /\brobots\.txt\b/i },
  { term: "Crawl and index", match: /\bcrawl(s|ed|ing|er)?\b|\bindex(ed|ing|es)\b/i },
  { term: "Google Search Console", match: /\bSearch Console\b/i },
  { term: "Google Business Profile", match: /\bGoogle Business Profiles?\b|\bGBP\b/ },
  { term: "SEO audit", match: /\baudits?\b/i },
  // Portfolio and selling
  { term: "Portfolio", match: /\bportfolios?\b/i },
  { term: "Case study", match: /\bcase stud(y|ies)\b/i },
  { term: "Concept project", match: /\bconcept (project|redesign|work)s?\b/i },
  { term: "Niche", match: /\bniches?\b/i },
  { term: "Scope", match: /\bscope\b/i },
  { term: "Floor price", match: /\bfloor prices?\b/i },
  { term: "Proposal", match: /\bproposals?\b/i },
  { term: "Prospect", match: /\bprospects?\b|\bprospecting\b/i },
  { term: "Follow-up", match: /\bfollow-ups?\b/i },
  { term: "Cold outreach", match: /\bcold (outreach|messages?|DMs?|pitch(es)?)\b/i },
  { term: "Care plan", match: /\bcare plans?\b|\bretainers?\b/i },
  { term: "Milestone", match: /\bmilestones?\b/i },
  { term: "Scope creep", match: /\bscope creep\b/i },
  // Main Track: local SEO and content
  { term: "Map pack", match: /\bmap pack\b/i },
  { term: "Service-area business", match: /\bservice[- ]area\b/i },
  { term: "NAP", match: /\bNAP\b/ },
  { term: "Citation", match: /\bcitations?\b/i },
  { term: "Content brief", match: /\bcontent briefs?\b/i },
  // Main Track: automation
  { term: "Automation", match: /\bautomat(e|es|ed|ing|ion|ions)\b/i },
  { term: "Workflow", match: /\bworkflows?\b/i },
  { term: "Trigger", match: /\btriggers?\b/i },
  { term: "ROI", match: /\bROI\b|\breturn on investment\b/i },
  { term: "Module", match: /\bmodules?\b/i },
  { term: "Operation", match: /\boperations?\b/i },
  { term: "Token", match: /\btokens?\b/i },
  // Main Track: agents
  { term: "AI model", match: /\bAI models?\b|\blanguage models?\b|\bLLMs?\b/i },
  { term: "AI agent", match: /\bAI agents?\b|\bchat agents?\b|\bsupport agents?\b/i },
  { term: "System prompt", match: /\bsystem prompts?\b/i },
  { term: "Knowledge base", match: /\bknowledge bases?\b/i },
  { term: "Hallucination", match: /\bhallucinat(e|es|ed|ion|ions|ing)\b/i },
  { term: "Test script", match: /\btest scripts?\b/i },
  { term: "Handoff", match: /\bhandoffs?\b/i },
  { term: "WhatsApp Business Platform", match: /\bCloud API\b|\bBusiness Platform\b/i },
  { term: "Customer service window", match: /\bservice window\b|\b24-hour window\b/i },
  { term: "Template message", match: /\btemplate messages?\b/i },
  { term: "Opt-in", match: /\bopt(ed)?[- ]in\b/i },
  // Main Track: the connected system
  { term: "CRM", match: /\bCRMs?\b/ },
  { term: "Lead", match: /\bleads\b|\b(hot|warm|cold|new|qualified) leads?\b/i },
  { term: "Unique key", match: /\bunique keys?\b|\bunique ID\b/i },
  { term: "Normalise", match: /\bnormali[sz](e|es|ed|ing|ation)\b/i },
  { term: "Pipeline", match: /\bpipelines?\b/i },
  { term: "Monitoring", match: /\bmonitor(s|ing|ed)?\b/i },
  { term: "Uptime", match: /\buptime\b/i },
  { term: "Runbook", match: /\brunbooks?\b/i },
  // Main Track: winning clients
  { term: "Funnel", match: /\bfunnels?\b/i },
  { term: "Scraping", match: /\bscrap(e|es|ed|ing|er|ers)\b/i },
  { term: "Lead magnet", match: /\blead magnets?\b/i },
  { term: "Qualification", match: /\bqualif(y|ied|ying|ication)\b/i },
  { term: "BANT", match: /\bBANT\b/ },
  { term: "Value-based pricing", match: /\bvalue-based\b/i },
  { term: "Capstone", match: /\bcapstone\b/i },
  { term: "Quality gate", match: /\bquality gates?\b/i },
];
